import { FunctionComponent } from 'react';
import Head from 'next/head';
import { imgPrefix } from '@/utils/path';

const Metadata: FunctionComponent = () => {
	return (
		<Head>
			<title>policyshop</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<meta
				property="og:title"
				content="เลือกตั้งรอบนี้พรรคคุณพี่ขายอะไรหรอคะ?"
			/>
			<meta
				property="og:description"
				content="เลือกตั้งรอบนี้พรรคคุณพี่ขายอะไรหรอคะ"
			/>
			<meta property="og:image" content={`${imgPrefix}/policy_og.jpg`} />
			<meta name="twitter:card" content="summary_large_image" />
		</Head>
	);
};

export default Metadata;
