import { useEffect, useState } from 'react';
import Layout from '@/components/Layout';
import Head from 'next/head';
import IntroPolicy from '@/components/Landing/IntroPolicy';
import HotTopicPolicy from '@/components/Landing/HotTopicPolicy';
import ByTopic from '@/components/Landing/ByTopic';
import ByParty from '@/components/Landing/ByParty';
import { TheyWorkForUs } from '@thailand-election-2023/database';
import { Party } from '@thailand-election-2023/database/src/models/party';
import { Policy } from '@thailand-election-2023/database/src/models/policy';
import { groupBy } from '@/utils';
import { GroupByTopics } from '@/types/components';
import ShortCut from '@/components/ShortCut';

export default function Landing() {
	const [hotParties, setHotParties] = useState<Party[]>([]);
	const [topics, setTopics] = useState<GroupByTopics>({});

	const fetchParties = async (): Promise<void> => {
		const data: Party[] = await TheyWorkForUs.Parties.fetchAll({
			where: '(PartyType,eq,พรรค)',
		});
		//mock get hot parties
		setHotParties(data.slice(0, 8));
	};

	const fetchPolicies = async (): Promise<void> => {
		const data: Policy[] = await TheyWorkForUs.Policies.fetchAll();
		setTopics(groupBy(data, 'Topic'));
	};
	useEffect(() => {
		fetchParties();
		fetchPolicies();
	}, []);
	return (
		<>
			<Head>
				<title>policyshop</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main>
				<Layout title="landing">
					<IntroPolicy />
					<ShortCut />
					<HotTopicPolicy topics={topics} />
					<ByTopic topics={topics} />
					<ByParty parties={hotParties} />
				</Layout>
			</main>
		</>
	);
}
