import { useEffect, useState } from 'react';
import Layout from '@/components/Layout';
import Head from 'next/head';
import IntroPolicy from '@/components/Landing/IntroPolicy';
import HotTopicPolicy from '@/components/Landing/HotTopicPolicy';
import ByTopic from '@/components/Landing/ByTopic';
import ByParty from '@/components/Landing/ByParty';
import { TheyWorkForUs } from '@thailand-election-2023/database';
import { Party } from '@thailand-election-2023/database/src/models/party';
import { Policy } from '@thailand-election-2023/database/src/models/policy';
import { groupBy } from '@/utils';
import { GroupByTopics, IDropdownOption } from '@/types/components';
import ShortCut from '@/components/ShortCut';
import AutoComplete from '@/components/Compare/AutoComplete';
import WvSharer from '@wevisdemo/ui/react/sharer';
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function Landing() {
	const [hotParties, setHotParties] = useState<Party[]>([]);
	const [parties, setParties] = useState<Party[]>([]);
	const [topics, setTopics] = useState<GroupByTopics>({});
	const [selectedPartyOption, setSelectedPartyOption] =
		useState<IDropdownOption<string> | null>(null);
	const router = useRouter();

	const fetchParties = async (): Promise<void> => {
		const data: Party[] = await TheyWorkForUs.Parties.fetchAll({
			where: '(PartyType,eq,พรรค)',
		});
		setParties(data);
		//mock get hot parties
		setHotParties(data.slice(0, 8));
	};

	const getPartyOptions = (): IDropdownOption<string>[] => {
		return parties.map((party) => ({
			label: party.Name,
			value: party.Name,
		}));
	};

	const onSelectParty = (option: IDropdownOption<string>) => {
		setSelectedPartyOption(option);
		router.push(`/party/${option.value}`);
	};

	const fetchPolicies = async (): Promise<void> => {
		const data: Policy[] = await TheyWorkForUs.Policies.fetchAll();
		setTopics(groupBy(data, 'Topic'));
	};
	useEffect(() => {
		fetchParties();
		fetchPolicies();
	}, []);
	return (
		<>
			<Head>
				<title>policyshop</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main>
				<Layout title="landing">
					<IntroPolicy />
					<div className="max-w-[728px] mx-auto">
						<ShortCut />
						<HotTopicPolicy topics={topics} />
						<ByTopic topics={topics} />
						<ByParty parties={hotParties} />

						<div className="mt-[16px]">
							<AutoComplete
								options={getPartyOptions()}
								currentOption={selectedPartyOption}
								onSelect={onSelectParty}
								placeholder="เลือกพรรค"
							/>
						</div>
						<div className="flex flex-col items-center my-[40px]">
							<div className="flex">
								{/* <WvSharer url={`www.google.com`} /> */}
							</div>
							<p className="font-bold typo-b3">#WeVisElection66</p>
							<Link href={'/about'}>
								<div className="font-bold py-[10px] px-[20px] border-[3px] rounded-[50px] w-fit mt-[10px]">
									เกี่ยวกับโครงการ
								</div>
							</Link>
						</div>
					</div>
					<election-footer></election-footer>
				</Layout>
			</main>
		</>
	);
}
